### ISSUE TITLE
Definir el diseño de los datos

### ISSUE THREAD

**Issue by alefuegom** [alefuegom/TFG_app#3]
- [x] Análisis de los requisitos
- [x] Definir el modelo de las entidades
- [ ] Creación de la base de datos
- [ ] Creación de las tablas necesarias
- [ ] Implementación de las entidades de la aplicación
