### ISSUE TITLE
Definir el diseño de la interfaz

### ISSUE THREAD

**Issue by alefuegom** [alefuegom/TFG_app#4]
- [ ] Definición de la estética general de la aplicación
- [ ] Definición de la estética para cada uno de los roles
- [ ] Definición de la estética de los artefactos de la aplicación
- [ ] Implementación de la estética general de la aplicación
- [ ] Implementación de la estética para cada uno de los roles
- [ ] Implementación de la estética de los artefactos de la aplicación
